set_property SRC_FILE_INFO {cfile:C:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/constrs_1/new/top.xdc rfile:../../../termp_template.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { start_button }]; #IO_L12N_T1_MRCC_35 Sch=btn[0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { done_led }]; #IO_L23P_T3_35 Sch=led[0]
