# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/ip/blk_rom/blk_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_rom || ORIG_REF_NAME==blk_rom} -quiet] -quiet

# XDC: c:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/ip/blk_rom/blk_rom_ooc.xdc

# XDC: c:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/ip/blk_rom/blk_rom.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_rom || ORIG_REF_NAME==blk_rom} -quiet] -quiet

# XDC: c:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/ip/blk_rom/blk_rom_ooc.xdc

# XDC: c:/Users/qwer/Desktop/DSD_2022/termp_bundle/vivado/termp_template/termp_template.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
